language: cpp

git:
  depth: 1000

os:
  - linux
  - osx
sudo: required
dist: trusty
osx_image: xcode8.3

install:
  - pushd build
  - ./download.sh
  - popd

script:
  - ulimit -n 4096
  - powershell -File build/travis.ps1